hujan_ui/installers/inventories/urls.py
from django.urls import path, include

from . import views

app_name = 'inventories'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('edit/<int:id>', views.edit, name='edit'),
    path('delete/<int:id>', views.delete, name='delete'),
]

hujan_ui/installers/servers/urls.py
from django.urls import path, include

from . import views

app_name = 'servers'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('edit/<int:id>', views.edit, name='edit'),
    path('delete/<int:id>', views.delete, name='delete'),
]

hujan_ui/installers/urls.py
from django.urls import path, include

from . import views

app_name = 'installer'
urlpatterns = [
    path('servers/', include('hujan_ui.installers.servers.urls')),
    path('inventories/', include('hujan_ui.installers.inventories.urls')),
    path('configurations/', include('hujan_ui.installers.configurations.urls')),
    path('global-config', views.global_config, name='global_config'),
    path('advanced-config', views.advanced_config, name='advanced_config'),
    path('deploy', views.deploy, name='deploy'),
    path('do_deploy', views.do_deploy, name='do_deploy'),
    path('deploy_log/<int:id>', views.deploy_log, name='deploy_log')
]

hujan_ui/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('hujan_ui.website.urls')),
    path('admin/', admin.site.urls),
    path('installer/', include('hujan_ui.installers.urls')),
    path('maas/', include('hujan_ui.maas.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

hujan_ui/installers/models.py
from django.db import models


class Server(models.Model):
    name = models.CharField(max_length=200)
    ip_address = models.CharField(max_length=100)
    description = models.CharField(max_length=220)
    system_id = models.CharField(max_length=220, help_text="unique id MAAS")

    def __str__(self):
        return self.name


class Inventory(models.Model):
    server = models.ForeignKey(Server, on_delete=models.CASCADE)
    GROUP = (
        ('control', 'Controller'),
        ('network', 'Network'),
        ('compute', 'Compute'),
        ('monitoring', 'Monitoring'),
        ('storage', 'storage'),
    )
    group = models.CharField(max_length=50, choices=GROUP)

    class Meta:
        verbose_name = "inventory"
        verbose_name_plural = "inventories"

    def __str__(self):
        return f"{self.server} - {self.group}"


class GlobalConfig(models.Model):
    INSTALLATION_TYPE = (
        ('source', 'Source'),
    )
    installation_type = models.CharField(max_length=50, choices=INSTALLATION_TYPE, default='source')
    OPENSTACK_RELEASE = (
        ('train', 'Train'),
    )
    openstack_release = models.CharField(max_length=50, choices=OPENSTACK_RELEASE, default='train')
    internal_vip_address = models.CharField(max_length=30)
    external_vip_address = models.CharField(max_length=30)
    enable_tls_on_external_api = models.BooleanField(default=True)
    enable_ceph_service = models.BooleanField(default=True)
    enable_cinder_service = models.BooleanField(default=True)
    enable_magnum_service = models.BooleanField(default=True)
    enable_vpnaas = models.BooleanField(default=True)
    enable_fwaas = models.BooleanField(default=True)
    enable_qos = models.BooleanField(default=True)
    enable_ha_agent = models.BooleanField(default=True)
    enable_provider_networks = models.BooleanField(default=True)
    enable_port_forwading = models.BooleanField(default=True)
    enable_octavia_service = models.BooleanField(default=True)
    enable_promotheus_service = models.BooleanField(default=True)
    ceph_pool_pg_num = models.IntegerField(default=30)
    ceph_pool_pgp_num = models.IntegerField(default=30)
    glance_backend_using_ceph = models.BooleanField(default=True)
    glance_backend_file = models.BooleanField(default=False)

    def __str__(self):
        return self.installation_type


class AdvancedConfig(models.Model):
    SERVICE_TYPE = (
        ('octavia_service', 'Octavia Service'),
        ('neutron_service', 'Neutron Service'),
        ('ml2_plugin', 'ML2 Plugin'),
        ('heat_service', 'Heat Service'),
        ('magnum_service', 'Magnum Service'),
    )
    service_type = models.CharField(max_length=50, choices=SERVICE_TYPE)
    configuration = models.TextField()

    def __str__(self):
        return self.service_type


class Deployment(models.Model):
    DEPLOY_IN_PROGRESS = "in_progress"
    DEPLOY_SUCCESS = "success"
    DEPLOY_FAILED = "failed"

    DEPLOY_STATUS = (
        (DEPLOY_IN_PROGRESS, "In Progress"),
        (DEPLOY_SUCCESS, "Success"),
        (DEPLOY_FAILED, "Failed")
    )

    log_name = models.CharField(max_length=255)
    status = models.CharField(max_length=255, choices=DEPLOY_STATUS)

hujan_ui/installers/configurations/forms.py
from django import forms

from hujan_ui.installers.models import GlobalConfig, AdvancedConfig


class GlobalConfigForm(forms.ModelForm):

    class Meta:
        model = GlobalConfig
        fields = ('__all__')


class AdvancedConfigForm(forms.ModelForm):

    class Meta:
        model = AdvancedConfig
        fields = ('__all__')

    def __init__(self, *args, **kwargs):
        """
        to avoid redundan service type
        """
        super().__init__(*args, **kwargs)
        service_type = AdvancedConfig.SERVICE_TYPE
        services_used = AdvancedConfig.objects.all()
        if self.instance.id:
            services_used = services_used.exclude(id=self.instance.id)

        services_available = ((k, v) for k, v in service_type if k not in services_used.values_list('service_type', flat=True))
        self.fields['service_type'].choices = tuple(services_available)
        

hujan_ui/installers/inventories/forms.py
from django import forms
from hujan_ui.installers.models import Inventory


class InventoryForm(forms.ModelForm):
    class Meta:
        model = Inventory
        fields = ('__all__')

hujan_ui/installers/servers/forms.py
from django import forms

from hujan_ui import maas
from hujan_ui.installers.models import Server


class AddServerForm(forms.ModelForm):
    machine = forms.ChoiceField(label='Name')

    class Meta:
        model = Server
        fields = ['machine','ip_address', 'description', 'system_id', 'name']
        widgets = {
            'ip_address': forms.Select(),
            'description': forms.TextInput(attrs={'required': False}),
            'system_id': forms.HiddenInput(),
            'name': forms.HiddenInput()
        }
        help_texts = {
            'description': 'Short description from this server',
        }

    def __init__(self, *args, **kwargs):
        self.machines = self.get_choices_machines()
        super().__init__(*args, **kwargs)
        self.fields['machine'].choices = self.machines
        if self.instance.system_id:
            self.fields['machine'].initial = self.instance.system_id

    def get_choices_machines(self):
        resp = maas.get_machines()
        return [
            (machine['system_id'], machine['fqdn']) for machine in resp
        ]

hujan_ui/installers/configurations/views.py
import sweetify

from django.utils.translation import ugettext_lazy as _
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from hujan_ui.installers.models import GlobalConfig, AdvancedConfig
from .forms import GlobalConfigForm, AdvancedConfigForm


@login_required
def global_config(request):
    global_config = GlobalConfig.objects.first()
    if not global_config:
        global_config = GlobalConfig.objects.create()
    form = GlobalConfigForm(request.POST or None, instance=global_config)
    if form.is_valid():
        form.save()
        sweetify.success(request, _("Successfully update global config"), button='OK', icon='success')
        return redirect("installer:configurations:global_config")

    context = {
        'title': _('Global Configuration'),
        'menu_active': 'global-configuration',
        'form': form
    }
    return render(request, 'installers/global-config-form.html', context)


@login_required
def advanced_config(request):
    advanced_config = AdvancedConfig.objects.all()

    context = {
        'title': _('Advanced Configuration'),
        'menu_active': 'advanced-configuration',
        'advanced_config': advanced_config
    }
    return render(request, 'installers/advanced-config.html', context)


@login_required
def add_advanced_config(request):
    form = AdvancedConfigForm(request.POST or None)

    if form.is_valid():
        form.save()
        sweetify.success(request, _("Successfully added advanced configuration"), button='OK', icon='success')
        return redirect("installer:configurations:advanced_config")

    context = {
        'title': _('Add Advanced Configuration'),
        'form': form,
        'menu_active': 'advanced-configuration',
        'title_submit': _('Save Advanced Configuration'),
        'col_size': '12',
    }
    return render(request, "installers/form.html", context)


@login_required
def edit_advanced_config(request, id):
    advanced_config = get_object_or_404(AdvancedConfig, id=id)
    form = AdvancedConfigForm(data=request.POST or None, instance=advanced_config)
    if form.is_valid():
        form.save()
        sweetify.success(request, _("Successfully edited advanced configuration"), button='OK', icon='success')
        return redirect("installer:configurations:advanced_config")

    context = {
        'title': _('Edit Advanced Configuration'),
        'form': form,
        'menu_active': 'advanced-configuration',
        'title_submit': _('Edit Advanced Configuration'),
        'col_size': '12',
    }
    return render(request, "installers/form.html", context)


@login_required
def delete_advanced_config(request, id):
    advanced_config = get_object_or_404(AdvancedConfig, id=id)
    advanced_config.delete()
    sweetify.success(request, _("Successfully deleted advanced configuration"), icon='success', button='OK')
    return redirect("installer:configurations:advanced_config")

hujan_ui/installers/inventories/views.py
import sweetify
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.translation import ugettext_lazy as _

from hujan_ui.installers.models import Inventory
from .forms import InventoryForm


@login_required
def index(request):
    inventories = Inventory.objects.select_related('server').all()
    context = {
        'title': _('Inventories'),
        'inventories': inventories,
        'menu_active': 'inventories',
    }
    return render(request, 'installers/inventory.html', context)


@login_required
def add(request):
    form = InventoryForm(request.POST or None)

    if form.is_valid():
        form.save()
        sweetify.success(request, _("Successfully added inventory"), button='OK', icon='success')
        return redirect("installer:inventories:index")

    context = {
        'title': _('Add Inventory'),
        'form': form,
        'menu_active': 'inventories',
        'title_submit': _('Save Inventory'),
        'col_size': '12',
    }
    return render(request, "installers/form.html", context)


@login_required
def edit(request, id):
    inventory = get_object_or_404(Inventory, id=id)
    form = InventoryForm(data=request.POST or None, instance=inventory)
    if form.is_valid():
        form.save()
        sweetify.success(request, _("Successfully edited inventory"), button='OK', icon='success')
        return redirect("installer:inventories:index")

    context = {
        'title': _('Edit Inventory'),
        'form': form,
        'menu_active': 'inventories',
        'title_submit': _('Edit Inventory'),
        'col_size': '12',
    }
    return render(request, "installers/form.html", context)


@login_required
def delete(request, id):
    inventory = get_object_or_404(Inventory, id=id)
    inventory.delete()
    sweetify.success(request, _("Successfully deleted inventory"), icon='success', button='OK')
    return redirect("installer:inventories:index")

hujan_ui/installers/servers/views.py
import requests
import json
import sweetify

from django.utils.translation import ugettext_lazy as _
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from hujan_ui.installers.models import Server
from .forms import AddServerForm


@login_required
def index(request):
    servers = Server.objects.all()
    context = {
        'title': _('Servers'),
        'servers': servers,
        'system_ids': ",".join([s.system_id for s in servers]),
        'menu_active': 'add-server'
    }
    return render(request, 'installers/server.html', context)


@login_required
def add(request):
    form = AddServerForm(request.POST or None)

    if form.is_valid():
        form.save()
        sweetify.success(request, _("Successfully added server"), button='OK', icon='success')
        return redirect("installer:servers:index")

    context = {
        'title': _('Add Server'),
        'form': form,
        'menu_active': 'add-server',
        'title_submit': _('Save Server'),
        'col_size': '12',
    }
    return render(request, "installers/add-server.html", context)


@login_required
def edit(request, id):
    server = get_object_or_404(Server, id=id)
    form = AddServerForm(data=request.POST or None, instance=server)
    if form.is_valid():
        form.save()
        sweetify.success(request, _("Successfully edited server"), button='OK', icon='success')
        return redirect("installer:servers:index")

    context = {
        'title': _('Edit Server'),
        'form': form,
        'menu_active': 'servers',
        'title_submit': _('Edit Server'),
        'col_size': '12',
        'old_ip_address': server.ip_address
    }
    return render(request, "installers/add-server.html", context)


@login_required
def delete(request, id):
    server = get_object_or_404(Server, id=id)
    server.delete()
    sweetify.success(request, _("Successfully deleted server"), icon='success', button='OK')
    return redirect("installer:servers:index")

hujan_ui/installers/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404

from hujan_ui.installers.models import (
    Server, Inventory, GlobalConfig, AdvancedConfig,
    Deployment)
from hujan_ui.utils.deployer import Deployer


@login_required
def server(request):
    context = {
        'title': 'Servers',
        'menu_active': 'add-server'
    }
    return render(request, 'installers/server.html', context)


@login_required
def inventory(request):
    context = {
        'title': 'Inventory',
        'menu_active': 'inventory'
    }
    return render(request, 'installers/inventory.html', context)


@login_required
def global_config(request):
    context = {
        'title': 'Global Configuration',
        'menu_active': 'global-config'
    }
    return render(request, 'installers/global_config.html', context)


@login_required
def advanced_config(request):
    context = {
        'title': 'Advanced Configuration',
        'menu_active': 'advanced-config'
    }
    return render(request, 'installers/advanced_config.html', context)


@login_required
def deploy(request):
    context = {
        'title': 'Deploy',
        'menu_active': 'deploy',
        'servers': Server.objects.all(),
        'inventories': Inventory.objects.select_related('server').all(),
        'advanced_config': AdvancedConfig.objects.all(),
        'global_config': GlobalConfig.objects.first()
    }
    return render(request, 'installers/deploy.html', context)


@login_required
def do_deploy(request):
    deployer = Deployer()
    if not deployer.is_deploying():
        deployer.deploy()

    context = {
        "deployment": deployer.deployment_model
    }
    return render(request, 'installers/deploy_progress.html', context)


def deploy_log(request, id):
    from_line = request.GET.get("from_line", 0)
    deployment_model = get_object_or_404(Deployment, id=id)
    deployer = Deployer(deployment_model=deployment_model)
    return JsonResponse(data={
        "deployment": {
            "id": deployer.deployment_model.id,
            "status": deployer.deployment_model.status
        },
        "log": deployer.get_log(int(from_line))
    })

templates/installers/add-server.html
{% include 'installers/form.html' with form=form %}

{% block extra_js %}
<script>
    $( document ).ready(function() {
        {% if old_ip_address %}
            ajax_machine($("#id_machine").val());
        {% endif %}
    });

    $("#id_machine").on("change", function() {
        ajax_machine($(this).val());
    })

    function ajax_machine(systemID, ipAddress){
        var url = $(location).attr('origin') + "/maas/machines/" + systemID + "/details/"
        $.get(url, function(data, status) {
            // fill data
            $("#id_name").val(data.machine.fqdn)
            $("#id_system_id").val(data.machine.system_id)

            // check ip address
            var ipAddresses = data.machine.ip_addresses
            if (ipAddresses.length == 0 ) {
                alert("This server does not have an ip address")
                $("#id_ip_address").html("")
                return
            }

            // add option ip addresses
            var htmlOption = []
            $.each(ipAddresses, function(index, value) {
                if("{{ old_ip_address }}" == value){
                    htmlOption.push("<option value='"+ value +"' selected>"+ value +"</option>")
                }else{
                    htmlOption.push("<option value='"+ value +"'>"+ value +"</option>")
                }
            })
            $("#id_ip_address").html(htmlOption.join())
        })
    }
</script>
{% endblock %}

templates/installers/advanced-config.html
{% extends 'master-installer.html' %}
{% load static %}

{% block content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="card">
          <div class="card-header">
            <span class="card-title">Service List</span>
            <div class="float-right">
              <a href="{% url 'installer:configurations:add_advanced_config' %}" class="btn btn-primary"><i class="fas fa-plus"></i>&nbsp;&nbsp;Add Configuration<a>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            {% if advanced_config %}
              {% for config in advanced_config %}
                <div class="card">
                  <div class="card-header">
                    <div class="card-title text-info"><h4>{{ config.get_service_type_display }}</h4></div>
                    <div class="card-tools">
                      <!-- Collapse Button -->
                        <a href="{% url 'installer:configurations:edit_advanced_config' config.id %}" class="btn btn-info"><i class="fas fa-edit"></i>&nbsp;&nbsp;Edit<a>
                        <button class="btn btn-danger delete-swal" data-url="{% url 'installer:configurations:delete_advanced_config' config.id %}" data-name="{{ config }}"><i class="fas fa-trash-alt"></i> Delete</button>
                    </div>
                    <!-- /.card-tools -->
                  </div>
                  <!-- /.card-header -->
                  <div class="card-body">
                    <pre>{{ config.configuration|safe }}</pre>
                  </div>
                  <!-- /.card-body -->
                </div>
                <!-- /.card -->
              {% endfor %}
            {% else %}
              <h3>No Configurations</h3>
            {% endif %}
          </div>
          <div class="card-footer">
            <div class="float-right">
              <a href="{% url 'installer:configurations:global_config' %}" class="btn bg-navy"><i class="fas fa-arrow-circle-left"></i>&nbsp;&nbsp;&nbsp;Back</a>
              <a href="{% url 'installer:deploy' %}" class="btn bg-navy">Next&nbsp;&nbsp;&nbsp;<i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->

{% endblock %}

templates/installers/deploy.html
{% extends 'master-installer.html' %}
{% load static %}

{% block content %}
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Deploy Summary</h3>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <div class="card card-secondary">
              <div class="card-header">
                <h3 class="card-title">Servers</h3>
                <div class="card-tools">
                  <!-- Collapse Button -->
                  <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
                </div>
                <!-- /.card-tools -->
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th style="width:20%;">Description</th>
                      <th style="width:20%;">IP Address</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for server in servers %}
                    <tr>
                      <td>{{ server.name }}</td>
                      <td>{{ server.description }}</td>
                      <td>{{ server.ip_address }}</td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

            <div class="card card-secondary">
              <div class="card-header">
                <h3 class="card-title">Inventory</h3>
                <div class="card-tools">
                  <!-- Collapse Button -->
                  <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
                </div>
                <!-- /.card-tools -->
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table class="table table-bordered">
                  <thead>                  
                    <tr>
                      <th>Name</th>
                      <th style="width:20%;">IP Address</th>
                      <th style="width:20%;">Group</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for inventory in inventories %}
                      <tr>
                        <td>{{ inventory.server.name }}</td>
                        <td>{{ inventory.server.ip_address }}</td>
                        <td>{{ inventory.get_group_display }}</td>
                      </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

            <div class="card card-secondary">
              <div class="card-header">
                <h3 class="card-title">Global Configuration</h3>
                <div class="card-tools">
                  <!-- Collapse Button -->
                  <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
                </div>
                <!-- /.card-tools -->
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <div class="row">
                  <div class="col-md-5 mr-5">
                    <table class="table table-bordered">
                      <tr>
                        <th>Installation Type</th>
                        <td>{{ global_config.installation_type }}</td>
                      </tr>
                      <tr>
                        <th>Openstack Release</th>
                        <td>{{ global_config.openstack_release }}</td>
                      </tr>
                      <tr>
                        <th>Internal VIP Address</th>
                        <td>{{ global_config.internal_vip_address }}</td>
                      </tr>
                      <tr>
                        <th>External VIP Address</th>
                        <td>{{ global_config.external_vip_address }}</td>
                      </tr>
                      <tr>
                        <th>Enable TLS on External API</th>
                        <td>{{ global_config.enable_tls_on_external_api|yesno:"Yes,No" }}</td>
                      </tr>
                      <tr>
                        <th>Enable Ceph Service</th>
                        <td>{{ global_config.enable_ceph_service|yesno:"Yes,No" }}</td>
                      </tr>
                      <tr>
                        <th>Enable Cinder Service</th>
                        <td>{{ global_config.enable_cinder_service|yesno:"Yes,No" }}</td>
                      </tr>
                      <tr>
                        <th>Enable Magnum Service</th>
                        <td>{{ global_config.enable_magnum_service|yesno:"Yes,No" }}</td>
                      </tr>
                      <tr>
                        <th>Enable VPNaaS</th>
                        <td>{{ global_config.enable_vpnaas|yesno:"Yes,No" }}</td>
                      </tr>
                      <tr>
                        <th>Enable FWaaS</th>
                        <td>{{ global_config.enable_fwaas|yesno:"Yes,No" }}</td>
                      </tr>
                    </table>
                  </div>
                  <div class="col-md-5">
                    <table class="table table-bordered">
                      <tr>
                        <th>Enable QoS</th>
                        <td>{{ global_config.enable_qos|yesno:"Yes,No" }}</td>
                      </tr>
                      <tr>
                        <th>Enable HA Agent</th>
                        <td>{{ global_config.enable_ha_agent|yesno:"Yes,No" }}</td>
                      </tr>
                      <tr>
                        <th>Enable Provider Networks</th>
                        <td>{{ global_config.enable_provider_networks|yesno:"Yes,No" }}</td>
                      </tr>
                      <tr>
                        <th>Enable Port Forwarding</th>
                        <td>{{ global_config.enable_port_forwading|yesno:"Yes,No" }}</td>
                      </tr>
                      <tr>
                        <th>Enable Octavia Service</th>
                        <td>{{ global_config.enable_octavia_service|yesno:"Yes,No" }}</td>
                      </tr>
                      <tr>
                        <th>Enable Prometheus Service</th>
                        <td>{{ global_config.enable_promotheus_service|yesno:"Yes,No" }}</td>
                      </tr>
                      <tr>
                        <th>Ceph Pool - pg_num</th>
                        <td>{{ global_config.ceph_pool_pg_num }}</td>
                      </tr>
                      <tr>
                        <th>Ceph Pool - pgp_num</th>
                        <td>{{ global_config.ceph_pool_pgp_num }}</td>
                      </tr>
                      <tr>
                        <th>Glance Backend using Ceph</th>
                        <td>{{ global_config.glance_backend_using_ceph|yesno:"Yes,No" }}</td>
                      </tr>
                      <tr>
                        <th>Glance Backend File</th>
                        <td>{{ global_config.glance_backend_file|yesno:"Yes,No" }}</td>
                      </tr>
                    </table>
                  </div>
                </div>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->

            <div class="card card-secondary">
              <div class="card-header">
                <h3 class="card-title">Advanced Configuration</h3>
                <div class="card-tools">
                  <!-- Collapse Button -->
                  <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
                </div>
                <!-- /.card-tools -->
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                {% if advanced_config %}
                  {% for config in advanced_config %}
                    <div class="card">
                      <div class="card-header">
                        <div class="card-title text-info"><h4>{{ config.get_service_type_display }}</h4></div>
                      </div>
                      <!-- /.card-header -->
                      <div class="card-body">
                        <pre>{{ config.configuration|safe }}</pre>
                      </div>
                      <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                  {% endfor %}
                {% else %}
                  <h3>No Configurations</h3>
                {% endif %}
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <div class="card-footer">
            <div class="float-right">
              <a href="{% url 'installer:configurations:advanced_config' %}" class="btn bg-navy"><i class="fas fa-arrow-circle-left"></i>&nbsp;&nbsp;&nbsp;Back</a>
              <a href="{% url 'installer:do_deploy' %}" class="btn bg-info">Deploy&nbsp;&nbsp;&nbsp;<i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->

{% endblock %}