hujan_ui/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('hujan_ui.website.urls')),
    path('admin/', admin.site.urls),
    path('installer/', include('hujan_ui.installers.urls')),
    path('maas/', include('hujan_ui.maas.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

hujan_ui/website/urls.py
from django.urls import path

from . import views


app_name = 'website'
urlpatterns = [
    path('', views.dashboard, name='dashboard'),
]

templates/partials/css.html
{% load static %}

<!-- Font Awesome Icons -->
<link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
<!-- Theme style -->
<link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<!-- Tempusdominus Bbootstrap 4 -->
<link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
<!-- iCheck -->
<link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
<!-- JQVMap -->
<link rel="stylesheet" href="{% static 'plugins/jqvmap/jqvmap.min.css' %}">
<!-- overlayScrollbars -->
<link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
<!-- Daterange picker -->
<link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css' %}">
<!-- summernote -->
<link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.css' %}">
<!-- Google Font: Source Sans Pro -->
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

templates/partials/footer.html
<!-- Main Footer -->
<footer class="main-footer">
<!-- To the right -->
<div class="float-right d-none d-sm-inline">

</div>
<!-- Default to the left -->
<strong>&copy; {% now "Y" %} <a href="https://hujan.io/">hujan.io</a>.</strong> All rights reserved.
</footer>

templates/partials/header-navbar.html
{% load static %}

<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light border-bottom-0">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
        {% comment %} <a href="index3.html" class="nav-link">Home</a> {% endcomment %}
        </li>
        <li class="nav-item d-none d-sm-inline-block">
        {% comment %} <a href="#" class="nav-link">Contact</a> {% endcomment %}
        </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
        <!-- <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
            <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
            </button>
        </div>
        </div> -->
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Notifications Dropdown Menu -->
        <!-- <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">15</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-header">15 Notifications</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                <i class="fas fa-envelope mr-2"></i> 4 new messages
                <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                <i class="fas fa-users mr-2"></i> 8 friend requests
                <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                <i class="fas fa-file mr-2"></i> 3 new reports
                <span class="float-right text-muted text-sm">2 days</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
            </div>
        </li> -->

        <!-- user profile-->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <img src="{% static 'images/avatar_placeholder.png' %}" style="max-height:100%" class="img-circle elevation-2" alt="User Image">
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-header">{{ user.first_name }} {{ user.last_name }}</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-user mr-2"></i> Profile
                    <span class="float-right text-muted text-sm"><i class="right fas fa-angle-right"></i></span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-cog mr-2"></i> Settings
                    <span class="float-right text-muted text-sm"><i class="right fas fa-angle-right"></i></span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="{% url 'logout' %}" class="dropdown-item dropdown-footer">Sign out</a>
            </div>
        </li>
    </ul>
</nav>
<!-- /.navbar -->

templates/partials/js.html
{% load static %}

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>

<!-- Global Script -->

<script>
    $(".delete-swal").on("click", function() {
      var button = $(this);
      var url = button.data('url');
      var name = button.data('name');
  
      Swal.fire({
        title: 'Are you sure to delete '+ name +'?',
        text: "You won't be able to revert this!",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Yes, delete it!'
      }).then((result) => {
        if (result.value) {
          window.location = url;
        }
      });
    });
</script>

templates/partials/side-navbar-installer.html
{% load static %}

<!-- Main Sidebar Container -->
<aside class="main-sidebar elevation-4 sidebar-light-primary">
    <!-- Brand Logo -->
    <a href="{% url 'website:dashboard' %}" class="brand-link">
        <span class="brand-text font-weight-light">
        <img src="{% static 'images/logo.svg' %}" width="150px;">
        </span>
    </a>


    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
            <img src="{% static 'images/avatar_placeholder.png' %}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
            <a href="#" class="d-block">{{ user.username }}</a>
        </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
                with font-awesome or any other icon font library -->

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">

                <!-- Timelime example  -->
                <div class="row">
                    <div class="col-md-12">
                    <!-- The time line -->
                    <div class="timeline" style="margin-left:-12px; white-space:''">
                        <!-- timeline item -->
                        <div>
                            <i class="fas fa-angle-down bg-olive"></i>
                            <div class="timeline-item">
                                <a href="{% url 'installer:servers:index' %}" class="bg-olive nav-link">
                                    <p>Add Server</p>
                                </a>
                            </div>
                        </div>
                        <div>
                            <i class="far fa-circle bg-info"></i>
                            <div class="timeline-item">
                                <a href="#" class="bg-info nav-link">
                                    <p>Inventory</p>
                                </a>
                            </div>
                        </div>
                        <div>
                            <i class="fas fa-angle-down bg-default"></i>
                            <div class="timeline-item">
                                <button class="btn nav-link" disabled>
                                    <p>Global Configuration</p>
                                </button>
                            </div>
                        </div>

                        <div>
                            <i class="fas fa-angle-down bg-default"></i>
                            <div class="timeline-item">
                                <button class="btn nav-link" disabled>
                                    <p>Advanced Config</p>
                                </button>
                            </div>
                        </div>

                        <div>
                            <i class="fas fa-angle-down bg-default"></i>
                            <div class="timeline-item">
                                <button class="btn nav-link" disabled>
                                    <p>Deploy</p>
                                </button>
                            </div>
                        </div>
                        <div>
                            <i class="fas fa-check bg-default"></i>
                        </div>
                        <!-- END timeline item -->
                    </div>
                    </div>
                    <!-- /.col -->
                </div>
                </div>
                <!-- /.timeline -->

            </section>
      <!-- /.content -->
        </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

templates/partials/side-navbar.html
{% load static %}

<!-- Main Sidebar Container -->
<aside class="main-sidebar elevation-4 sidebar-light-info">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
        <span class="brand-text font-weight-light">
        <img src="{% static 'images/logo.svg' %}" width="150px;">
        </span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{% static 'images/avatar_placeholder.png' %}" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{ user.username }}</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
                with font-awesome or any other icon font library -->
            <li class="nav-item">
                <a href="{% url 'website:dashboard' %}" class="nav-link {% if menu_active == 'dashboard' %}active{% endif %}">
                    <i class="nav-icon fas fa-tachometer-alt"></i>
                    <p>Dashboard</p>
                </a>
            </li>

            <li class="nav-item">
                <a href="{% url 'installer:servers:index' %}" class="nav-link">
                    <i class="nav-icon fas fa-window-maximize"></i>
                    <p>Installer</p>
                </a>
            </li>
            <hr>
            <li class="nav-item">
                <a href="#" class="nav-link {% if menu_active == 'machines' %}active{% endif %}">
                    <i class="nav-icon fas fa-microchip"></i>
                    <p>Machines<i class="right fas fa-angle-left"></i></p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="{% url 'maas:machines:index' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Data Machines</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'maas:machines:add' %}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Add Machine</p>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="nav-item">
                <a href="#" class="nav-link {% if menu_active == 'lain' %}active{% endif %}">
                    <i class="nav-icon fas fa-network-wired"></i>
                    <p>Subnet<i class="right fas fa-angle-left"></i></p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Add Fabric</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Add VLAN</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Add Space</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Add Subnet</p>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="nav-item">
                <a href="#" class="nav-link {% if menu_active == 'images' %}active{% endif %}">
                    <i class="nav-icon fas fa-compact-disc"></i>
                    <p>Images</p>
                </a>
            </li>

            <li class="nav-item">
                <a href="#" class="nav-link {% if menu_active == 'lain' %}active{% endif %}">
                    <i class="nav-icon fas fa-cogs"></i>
                    <p>Controller<i class="right fas fa-angle-left"></i></p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Data Controllers</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Add Rack Controller</p>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="nav-item">
                <a href="{% url 'maas:dns:index' %}" class="nav-link {% if menu_active == 'domains' %}active{% endif %}">
                    <i class="nav-icon fas fa-globe-asia"></i>
                    <p>DNS</p>
                </a>
            </li>

            <li class="nav-item">
                <a href="#" class="nav-link {% if menu_active == 'lain' %}active{% endif %}">
                    <i class="nav-icon fas fa-wrench"></i>
                    <p>Settings<i class="right fas fa-angle-left"></i></p>
                </a>
                <ul class="nav nav-treeview">
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>User</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>General</p>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>